languageCode = "ru"
languageName = "Русский"
weight = 1
title = "Rotten Mechanism"

[params]
  displayName = "RU"
  isoCode = "ru"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  # secondaryLogo = "PATH"
  # description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
  copyright = "Copyright RM Team"

[author]
  name = "Rotten Mechanism"
  image = "img/blowfish_logo.png"
  headline = "Опаньки, здраасти^^"
  # bio = "Тут био"
  # links = [
  #     { github = "https://github.com/kainsamara" },
  # ]

  