languageCode = "ru"
languageName = "Русский"
weight = 1
title = "Rotten Mechanism"

[params]
  displayName = "RU"
  isoCode = "ru"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/rotten_logo_transparent.png"
  # secondaryLogo = "img/rotten_logo_transparent.png"
  # description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
  copyright = "© RM, 2K24"

[author]
  name = "Rotten Mechanism"
  image = "img/rotten_logo.png"
  headline = "Опаньки, здраасти :))"
  bio = "Как жеж вас сюда занесло?"
  # links = [
  #     { github = "https://github.com/kainsamara" },
  # ]

  